# Generated by Django 4.0.3 on 2022-03-28 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ClientHome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_verified',
        ),
    ]
